name: 🐛 Bug report
description: Create a bug report to help me improve 'Take you there' 🗺️
title: "Bug: "
labels: [👀 needs triage, 🐛 bug]
body:
  - type: markdown
    attributes:
      value: |
        Hey, dear! Thank you immensely for taking the time to fill out this bug report!
  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Describe how to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        # An image might be worth 100 words!
        This will help me to get a better understanding of the issue.
  - type: textarea
    attributes:
      label: Do you have any screenshots?
      description: A clear image showing the bad behavior would be awesome. If not available, write N/A.
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/JuditKaramazov/TakeYouThere/blob/main/CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
  - type: checkboxes
    id: contribution
    attributes:
      label: Contributing Docs
      description: If you plan on contributing, please read our [Contribution Guide](https://github.com/JuditKaramazov/TakeYouThere/blob/main/CONTRIBUTING.md) first.
      options:
        - label: I agree to follow this project's Contribution Docs
          required: false